### ISSUE TITLE
Mute & Bixby button

### ISSUE THREAD

**Issue by nexussmart** [flutter-moum/flutter_hardware_buttons#31]
Hi,

Do you integrate the detection of mute and bixby buttons?

Thanks

**Comment by eojine** [comment]
@nexussmart

Hi.

We are considering the additional button detection you said.
I'll test it first, and if it's feasible, I'll answer it again.

thanks

**Comment by nexussmart** [comment]
Hi,

Thank you for your answer.

A link that could help you : https://github.com/akramhussein/Mute ?

**Comment by eojine** [comment]
@nexussmart
Hi.

I'm sorry but we can't add Bixby buttons and mute buttons. Because Bixby button and Mute button do not provide API.
In addition, [the posting](https://github.com/akramhussein/Mute) indicates whether it is a mute or not using a short-sounding trigger every second. This is different from the direction we intend to develop.

So we decided not to add button detection.

Thank you.
